version: "3.9"

networks:
  traefik_network:
    external: true

services:

  app-dev:
    container_name: aposturch-admin-app-dev
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: aposturch-admin-app-dev
    volumes:
      - .:/var/www/html
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aposturch-admin-app-dev.rule=Host(`app-aposturch-admin.docker.localhost`)"
      - "traefik.http.services.aposturch-admin-app-dev.loadbalancer.server.port=8080"
      - "traefik.http.routers.aposturch-admin-app-dev.tls=true"

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: aposturch-admin-node
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html
    networks:
      - traefik_network
    ports:
      - 3000:3000
      - 3001:3001