export const subjects = {
  ROOT: 'ROOT',
  ADMIN_USERS_VIEW: 'ADMIN_USERS_VIEW',
  ADMIN_USERS_INSERT: 'ADMIN_USERS_INSERT',
  ADMIN_USERS_UPDATE: 'ADMIN_USERS_UPDATE',
  CUSTOMERS: 'CUSTOMERS',
}

export const actions = {
  VIEW: 'VIEW',
  INSERT: 'INSERT',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
}
