export const subjects = {
  ROOT: 'ROOT',

  ADMIN_USERS_VIEW: 'ADMIN_USERS_VIEW',
  ADMIN_USERS_INSERT: 'ADMIN_USERS_INSERT',
  ADMIN_USERS_UPDATE: 'ADMIN_USERS_UPDATE',
  ADMIN_USERS_DELETE: 'ADMIN_USERS_DELETE',

  ADMIN_USERS_ADMIN_MASTER: 'ADMIN_USERS_ADMIN_MASTER',
  ADMIN_USERS_ADMIN_CHURCH: 'ADMIN_USERS_ADMIN_CHURCH',
  ADMIN_USERS_ADMIN_MODULE: 'ADMIN_USERS_ADMIN_MODULE',
  ADMIN_USERS_ADMIN_ASSISTANT: 'ADMIN_USERS_ADMIN_ASSISTANT',
  ADMIN_USERS_ADMIN_MEMBER: 'ADMIN_USERS_ADMIN_MEMBER',

  FINANCE_MODULE: 'FINANCE_MODULE',
  STORE_MODULE: 'STORE_MODULE',
  GROUPS_MODULE: 'GROUPS_MODULE',
  MEMBERS_MODULE: 'MEMBERS_MODULE',
  SCHEDULE_MODULE: 'SCHEDULE_MODULE',
  PATRIMONY_MODULE: 'PATRIMONY_MODULE',
  USERS_MODULE: 'USERS_MODULE',
}

export const actions = {
  VIEW: 'VIEW',
  INSERT: 'INSERT',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
}
